import type { Metadata } from "next";
import { Sometype_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import { MainNav } from "@/components/MainNav";

const sometypeMono = Sometype_Mono({
  variable: "--font-primary",
  subsets: ["latin"],
});

const playfair = Playfair_Display({
  variable: "--font-secondary",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${sometypeMono.variable} ${playfair.variable} antialiased`}
      >
        <div className="flex">
          <div className="hidden xl:flex w-[285px] h-screen bg-secondary">
            <MainNav />
          </div>
          <div className="w-full max-w-[1130px] px-[15px] mx-auto bg-pink-50/10">
            <header>header</header>
            <div>{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
